name: Release
on:
  push:
    tags:
      - '*'

jobs:
  ter-publish:
    uses: maikschneider/reusable-workflows/.github/workflows/release.yml@main
    secrets:
      typo3-api-token: ${{ secrets.TYPO3_API_TOKEN }}
    with:
      typo3-extension-key: 'bw_focuspoint_images'
